/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameManifestEntry } from './manifest.types';

import entry0 from './cardia/manifest';
import entry1 from './dicethrone/manifest';
import entry2 from './smashup/manifest';
import entry3 from './summonerwars/manifest';
import entry4 from './tictactoe/manifest';

export const GAME_MANIFEST: GameManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
];

export const GAME_MANIFEST_BY_ID: Record<string, GameManifestEntry> = Object.fromEntries(
    GAME_MANIFEST.map((entry) => [entry.id, entry])
);
