/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameClientManifestEntry, GameClientRuntimeModule } from './manifest.client.types';
import { ManifestGameThumbnail } from '../components/lobby/thumbnails';

import manifest0 from './cardia/manifest';
import Thumbnail0 from './cardia/thumbnail';

import manifest1 from './dicethrone/manifest';
import Thumbnail1 from './dicethrone/thumbnail';

import manifest2 from './smashup/manifest';
import Thumbnail2 from './smashup/thumbnail';

import manifest3 from './summonerwars/manifest';
import Thumbnail3 from './summonerwars/thumbnail';

import manifest4 from './tictactoe/manifest';
import Thumbnail4 from './tictactoe/thumbnail';

const loadRuntime0 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, tutorialModule] = await Promise.all([
        import('./cardia/game'),
        import('./cardia/Board'),
        import('./cardia/tutorial'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        tutorial: tutorialModule.default,
    };
};

const loadRuntime1 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, tutorialModule, latencyModule] = await Promise.all([
        import('./dicethrone/game'),
        import('./dicethrone/Board'),
        import('./dicethrone/tutorial'),
        import('./dicethrone/latencyConfig'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        tutorial: tutorialModule.default,
        latencyConfig: latencyModule.diceThroneLatencyConfig,
    };
};

const loadRuntime2 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, tutorialModule, latencyModule] = await Promise.all([
        import('./smashup/game'),
        import('./smashup/Board'),
        import('./smashup/tutorial'),
        import('./smashup/latencyConfig'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        tutorial: tutorialModule.default,
        latencyConfig: latencyModule.smashUpLatencyConfig,
    };
};

const loadRuntime3 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, tutorialModule, latencyModule] = await Promise.all([
        import('./summonerwars/game'),
        import('./summonerwars/Board'),
        import('./summonerwars/tutorial'),
        import('./summonerwars/latencyConfig'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        tutorial: tutorialModule.default,
        latencyConfig: latencyModule.summonerWarsLatencyConfig,
    };
};

const loadRuntime4 = async (): Promise<GameClientRuntimeModule> => {
    const [gameModule, boardModule, tutorialModule, latencyModule] = await Promise.all([
        import('./tictactoe/game'),
        import('./tictactoe/Board'),
        import('./tictactoe/tutorial'),
        import('./tictactoe/latencyConfig'),
    ]);
    return {
        engineConfig: gameModule.engineConfig,
        board: boardModule.default,
        tutorial: tutorialModule.default,
        latencyConfig: latencyModule.ticTacToeLatencyConfig,
    };
};

const entry0: GameClientManifestEntry = {
    manifest: manifest0,
    thumbnail: <Thumbnail0 />,
    loadRuntime: loadRuntime0,
};

const entry1: GameClientManifestEntry = {
    manifest: manifest1,
    thumbnail: <Thumbnail1 />,
    loadRuntime: loadRuntime1,
};

const entry2: GameClientManifestEntry = {
    manifest: manifest2,
    thumbnail: <Thumbnail2 />,
    loadRuntime: loadRuntime2,
};

const entry3: GameClientManifestEntry = {
    manifest: manifest3,
    thumbnail: <Thumbnail3 />,
    loadRuntime: loadRuntime3,
};

const entry4: GameClientManifestEntry = {
    manifest: manifest4,
    thumbnail: <Thumbnail4 />,
    loadRuntime: loadRuntime4,
};

export const GAME_CLIENT_MANIFEST: GameClientManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
];

export const GAME_CLIENT_MANIFEST_BY_ID: Record<string, GameClientManifestEntry> = Object.fromEntries(
    GAME_CLIENT_MANIFEST.map((entry) => [entry.manifest.id, entry])
);
