/* eslint-disable */
// AUTO-GENERATED by scripts/game/generate_game_manifests.js. DO NOT EDIT.
import type { GameClientManifestEntry } from './manifest.client.types';
import { ManifestGameThumbnail } from '../components/lobby/thumbnails';

import manifest0 from './archview/manifest';
import Thumbnail0 from './archview/thumbnail';

import manifest1 from './assetslicer/manifest';
import Thumbnail1 from './assetslicer/thumbnail';

import manifest2 from './audiobrowser/manifest';
import Thumbnail2 from './audiobrowser/thumbnail';

import manifest3 from './dicethrone/manifest';
import { engineConfig as engineConfig3 } from './dicethrone/game';
import Board3 from './dicethrone/Board';
import Tutorial3 from './dicethrone/tutorial';
import Thumbnail3 from './dicethrone/thumbnail';

import manifest4 from './fxpreview/manifest';
import Thumbnail4 from './fxpreview/thumbnail';

import manifest5 from './smashup/manifest';
import { engineConfig as engineConfig5 } from './smashup/game';
import Board5 from './smashup/Board';
import Tutorial5 from './smashup/tutorial';
import Thumbnail5 from './smashup/thumbnail';

import manifest6 from './summonerwars/manifest';
import { engineConfig as engineConfig6 } from './summonerwars/game';
import Board6 from './summonerwars/Board';
import Tutorial6 from './summonerwars/tutorial';
import Thumbnail6 from './summonerwars/thumbnail';

import manifest7 from './tictactoe/manifest';
import { engineConfig as engineConfig7 } from './tictactoe/game';
import Board7 from './tictactoe/Board';
import Tutorial7 from './tictactoe/tutorial';
import Thumbnail7 from './tictactoe/thumbnail';

import manifest8 from './ugcbuilder/manifest';
import Thumbnail8 from './ugcbuilder/thumbnail';

const entry0: GameClientManifestEntry = {
    manifest: manifest0,
    thumbnail: <Thumbnail0 />,
};

const entry1: GameClientManifestEntry = {
    manifest: manifest1,
    thumbnail: <Thumbnail1 />,
};

const entry2: GameClientManifestEntry = {
    manifest: manifest2,
    thumbnail: <Thumbnail2 />,
};

const entry3: GameClientManifestEntry = {
    manifest: manifest3,
    engineConfig: engineConfig3,
    board: Board3,
    tutorial: Tutorial3,
    thumbnail: <Thumbnail3 />,
};

const entry4: GameClientManifestEntry = {
    manifest: manifest4,
    thumbnail: <Thumbnail4 />,
};

const entry5: GameClientManifestEntry = {
    manifest: manifest5,
    engineConfig: engineConfig5,
    board: Board5,
    tutorial: Tutorial5,
    thumbnail: <Thumbnail5 />,
};

const entry6: GameClientManifestEntry = {
    manifest: manifest6,
    engineConfig: engineConfig6,
    board: Board6,
    tutorial: Tutorial6,
    thumbnail: <Thumbnail6 />,
};

const entry7: GameClientManifestEntry = {
    manifest: manifest7,
    engineConfig: engineConfig7,
    board: Board7,
    tutorial: Tutorial7,
    thumbnail: <Thumbnail7 />,
};

const entry8: GameClientManifestEntry = {
    manifest: manifest8,
    thumbnail: <Thumbnail8 />,
};

export const GAME_CLIENT_MANIFEST: GameClientManifestEntry[] = [
    entry0,
    entry1,
    entry2,
    entry3,
    entry4,
    entry5,
    entry6,
    entry7,
    entry8,
];

export const GAME_CLIENT_MANIFEST_BY_ID: Record<string, GameClientManifestEntry> = Object.fromEntries(
    GAME_CLIENT_MANIFEST.map((entry) => [entry.manifest.id, entry])
);
